# Generated by Django 5.1.3 on 2024-12-03 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='descripcion',
            field=models.CharField(default='Sin descripcion', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='libro',
            name='enlace',
            field=models.CharField(default='No problem', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='libro',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='libros/'),
        ),
    ]
